import addUser from "../../support/PageObject/addUser.cy";
const Data = require("../../fixtures/data.json");
const { generateRandomString } = require("../../support/utils");

describe("Add User Test", () => {
  const AddUSer = new addUser();
  const randomUsername = generateRandomString(8);

  it("FPQS14 - Add User - All Field", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.userNameInput).type(Data.validUserNameAdd);
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
  });
  it("FPQS15 - Add User - No Select User Role", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.userNameInput).type(randomUsername);
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageNoSelectUserRole).should("be.visible");
  });
  it("FPQS16 - Add User - Be Empty Employee Name", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.userNameInput).type(randomUsername);
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageEmptyEmployeeName).should("be.visible");
  });
  it("FPQS17 - Add User - No Select Status", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.userNameInput).type(randomUsername);
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageNoSelectStatus).should("be.visible");
  });
  it("FPQS18 - Add User - Be Empty Username", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageNoInputUserName).should("be.visible");
  });
  it("FPQS19 - Add User - Be Empty Password", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.userNameInput).type(randomUsername);
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageNoInputPassword).should("be.visible");
    cy.get(AddUSer.massagePasswordNoMatch).should("be.visible");
  });
  it("FPQS20 - Add User - Be Empty Confirm Password", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.userNameInput).type(randomUsername);
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massagePasswordNoMatch).should("be.visible");
  });
  it("FPQS21 - Add User - Input No Record Employee Name", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.invalidEmployeeName);
    cy.get(AddUSer.userNameInput).type(randomUsername);
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageNoRecordEmployeeName).should("be.visible");
  });
  it("FPQS22 - Add User - Fill in the existing Username", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.userNameInput).type(Data.validUserNameAdd);
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageExistingUsername).should("be.visible");
  });
  it("FPQS23 - Add User - Password No Number", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.passwordInput).type(Data.noNumberPassword);
    cy.get(AddUSer.massageNoNumberPassword).should("be.visible");
  });
  it("FPQS24 - Add User - Password and Confirm Password are not the same", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.passwordInput).type(Data.noNumberPassword);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.massagePasswordNoMatch).should("be.visible");
  });
  it("FPQS25 - Add User - Password Does Not Meet Terms", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.passwordInput).type(Data.noTermPassword);
    cy.get(AddUSer.massagePasswordNotTerm).should("be.visible");
  });
  it("FPQS66 - Add User - Username Does Not Meet Terms", () => {
    cy.login(Data.validUsername, Data.validPassword);
    cy.get(AddUSer.adminSidebarBtn).click();
    cy.get(AddUSer.newAddUser).click();
    cy.get(AddUSer.userRoleInput).click();
    cy.get(AddUSer.listbox).contains(Data.validUsername).click();
    cy.get(AddUSer.employeenameInput).type(Data.validEmployeeName);
    cy.get(AddUSer.listbox).contains(Data.validEmployeeName).click();
    cy.get(AddUSer.statusInput).click();
    cy.get(AddUSer.listbox).contains(Data.validStatusInput).click();
    cy.get(AddUSer.userNameInput).type(Data.noTermUsername);
    cy.get(AddUSer.passwordInput).type(Data.validPasswordAdd);
    cy.get(AddUSer.confirmPasswordInput).type(Data.validComfirmPasswordAdd);
    cy.get(AddUSer.saveBtn).click();
    cy.get(AddUSer.massageExistingUsername).should("be.visible");
  });
});
