import validLogin from "../../support/PageObject/login.cy";
import Organization from "../../support/PageObject/organizationpage.cy";
const Data = require("../../fixtures/data.json");

describe("Admin Menu - Organization", () => {
  const ValidLogin = new validLogin();
  const organization = new Organization();

  it("FPQS26 - Edit Organization Successfully", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.regNum).type(Data.validRegNum);
    cy.get(organization.taxID).clear();
    cy.get(organization.taxID).type(Data.validTaxID);
    cy.get(organization.genPhone).clear();
    cy.get(organization.genPhone).type(Data.validGenPhone);
    cy.get(organization.genFax).clear();
    cy.get(organization.genFax).type(Data.validGenFax);
    cy.get(organization.genEmail).clear();
    cy.get(organization.genEmail).type(Data.validGenEmail);
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress1).type(Data.validGenAddress1);
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genAddress2).type(Data.validGenAddress2);
    cy.get(organization.genCity).clear();
    cy.get(organization.genCity).type(Data.validGenCity);
    cy.get(organization.genState).clear();
    cy.get(organization.genState).type(Data.validGenState);
    cy.get(organization.genZip).clear();
    cy.get(organization.genZip).type(Data.validGenZip);
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });
  it("FPQS27 - Edit Organization Unsuccessfully - All Field Empty", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.regNum).clear();
    cy.get(organization.taxID).clear();
    cy.get(organization.genPhone).clear();
    cy.get(organization.genFax).clear();
    cy.get(organization.genEmail).clear();
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genCity).clear();
    cy.get(organization.genState).clear();
    cy.get(organization.genZip).clear();
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genSave).click();
    cy.get(organization.orgNameRequired);
  });

  it("FPQS28 - Edit Organization Successfully - Empty Registration Number", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.taxID).clear();
    cy.get(organization.taxID).type(Data.validTaxID);
    cy.get(organization.genPhone).clear();
    cy.get(organization.genPhone).type(Data.validGenPhone);
    cy.get(organization.genFax).clear();
    cy.get(organization.genFax).type(Data.validGenFax);
    cy.get(organization.genEmail).clear();
    cy.get(organization.genEmail).type(Data.validGenEmail);
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress1).type(Data.validGenAddress1);
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genAddress2).type(Data.validGenAddress2);
    cy.get(organization.genCity).clear();
    cy.get(organization.genCity).type(Data.validGenCity);
    cy.get(organization.genState).clear();
    cy.get(organization.genState).type(Data.validGenState);
    cy.get(organization.genZip).clear();
    cy.get(organization.genZip).type(Data.validGenZip);
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });

  it("FPQS29 - Edit Organization Successfully - Empty Tax ID", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.regNum).type(Data.validRegNum);
    cy.get(organization.taxID).clear();
    cy.get(organization.genPhone).clear();
    cy.get(organization.genPhone).type(Data.validGenPhone);
    cy.get(organization.genFax).clear();
    cy.get(organization.genFax).type(Data.validGenFax);
    cy.get(organization.genEmail).clear();
    cy.get(organization.genEmail).type(Data.validGenEmail);
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress1).type(Data.validGenAddress1);
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genAddress2).type(Data.validGenAddress2);
    cy.get(organization.genCity).clear();
    cy.get(organization.genCity).type(Data.validGenCity);
    cy.get(organization.genState).clear();
    cy.get(organization.genState).type(Data.validGenState);
    cy.get(organization.genZip).clear();
    cy.get(organization.genZip).type(Data.validGenZip);
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });

  it("FPQS30 - Edit Organization Successfully - Empty Phone", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.regNum).type(Data.validRegNum);
    cy.get(organization.taxID).clear();
    cy.get(organization.taxID).type(Data.validTaxID);
    cy.get(organization.genPhone).clear();
    cy.get(organization.genFax).clear();
    cy.get(organization.genFax).type(Data.validGenFax);
    cy.get(organization.genEmail).clear();
    cy.get(organization.genEmail).type(Data.validGenEmail);
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress1).type(Data.validGenAddress1);
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genAddress2).type(Data.validGenAddress2);
    cy.get(organization.genCity).clear();
    cy.get(organization.genCity).type(Data.validGenCity);
    cy.get(organization.genState).clear();
    cy.get(organization.genState).type(Data.validGenState);
    cy.get(organization.genZip).clear();
    cy.get(organization.genZip).type(Data.validGenZip);
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });

  it("FPQS31 - Edit Organization Successfully - Empty Fax", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.regNum).type(Data.validRegNum);
    cy.get(organization.taxID).clear();
    cy.get(organization.taxID).type(Data.validTaxID);
    cy.get(organization.genPhone).clear();
    cy.get(organization.genPhone).type(Data.validGenPhone);
    cy.get(organization.genFax).clear();
    cy.get(organization.genEmail).clear();
    cy.get(organization.genEmail).type(Data.validGenEmail);
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress1).type(Data.validGenAddress1);
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genAddress2).type(Data.validGenAddress2);
    cy.get(organization.genCity).clear();
    cy.get(organization.genCity).type(Data.validGenCity);
    cy.get(organization.genState).clear();
    cy.get(organization.genState).type(Data.validGenState);
    cy.get(organization.genZip).clear();
    cy.get(organization.genZip).type(Data.validGenZip);
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });

  it("FPQS32 - Edit Organization Successfully - Empty Email", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.regNum).type(Data.validRegNum);
    cy.get(organization.taxID).clear();
    cy.get(organization.taxID).type(Data.validTaxID);
    cy.get(organization.genPhone).clear();
    cy.get(organization.genPhone).type(Data.validGenPhone);
    cy.get(organization.genFax).clear();
    cy.get(organization.genFax).type(Data.validGenFax);
    cy.get(organization.genEmail).clear();
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress1).type(Data.validGenAddress1);
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genAddress2).type(Data.validGenAddress2);
    cy.get(organization.genCity).clear();
    cy.get(organization.genCity).type(Data.validGenCity);
    cy.get(organization.genState).clear();
    cy.get(organization.genState).type(Data.validGenState);
    cy.get(organization.genZip).clear();
    cy.get(organization.genZip).type(Data.validGenZip);
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });

  it("FPQS34 - Edit Organization Successfully - Empty Address", () => {
    cy.visit(ValidLogin.baseUrl);
    cy.get(ValidLogin.username).type(Data.validUsername);
    cy.get(ValidLogin.password).type(Data.validPassword);
    cy.get(ValidLogin.loginBtn).click();
    cy.get(organization.urlAdmin).click();
    cy.get(organization.dropMenu).click();
    cy.get(organization.genInfo).click();
    cy.get(organization.genEdit).click({ force: true });
    cy.get(organization.orgName).clear();
    cy.get(organization.orgName).type(Data.validOrgName);
    cy.get(organization.regNum).clear();
    cy.get(organization.regNum).type(Data.validRegNum);
    cy.get(organization.taxID).clear();
    cy.get(organization.taxID).type(Data.validTaxID);
    cy.get(organization.genPhone).clear();
    cy.get(organization.genPhone).type(Data.validGenPhone);
    cy.get(organization.genFax).clear();
    cy.get(organization.genFax).type(Data.validGenFax);
    cy.get(organization.genEmail).clear();
    cy.get(organization.genEmail).type(Data.validGenEmail);
    cy.get(organization.genAddress1).clear();
    cy.get(organization.genAddress2).clear();
    cy.get(organization.genCity).clear();
    cy.get(organization.genState).clear();
    cy.get(organization.genZip).clear();
    cy.get(organization.genClickCountry).click();
    cy.get(organization.genCountry).contains(Data.validGenCountry).click();
    cy.get(organization.genNotes).clear();
    cy.get(organization.genNotes).type(Data.validGenNotes);
    cy.get(organization.genSave).click();
    cy.get(organization.genSuccess);
  });
});
